#!/bin/sh
# minimize the current window, launch a GUI program, and optionally unminimize when done

# concat all args into a list of single-quoted shell strings
# (properly escapes quotations)
concat() {
	for i in "$@"; do
		printf %s\\n "$i" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/' \\\\/"
	done
	echo ' '
}

usage() {
	>&2 echo "expected $1"
	exit 1
}

[ "$1" ] || usage "command"
[ "$2" ] || usage "unminimize: true/false"

program="$1"
unminimize="$2"
shift 2

awesome-client '
	local c = client.focus
	c.minimized = true
	require("awful").spawn.easy_async_with_shell(
		[[cd "'"$PWD"'"; '"$program"' '"$(concat "$@")"']],
		function() '"$(
			[ "$unminimize" = 'true' ] && echo 'pcall(function() c.minimized = false end)'
		)"' end
	)
'
