#!/bin/sh
# yt - youtube
# simplify downloading youtube videos with yt-dlp

usage() {
    echo 'usage: yt <a|v> <format> <yt-dlp opts>'; exit 1
}

[ $# -lt 3 ] && usage

opt="$1"; shift
fmt="$1"; shift

case "$opt" in
    a) yt-dlp -f 'ba' -x --audio-quality 0 --audio-format "$fmt" "$@" ;;
    v) yt-dlp -f 'b' --remux-video "$fmt" "$@"                        ;;
    *) usage                                                          ;;
esac
