#!/bin/sh
# yt - youtube
# simplify downloading youtube videos with yt-dlp

usage() {
    echo 'usage: yt <a|v <format>> <yt-dlp opts>'; exit 1
}

[ $# -lt 2 ] && usage

opt="$1"; shift

case "$opt" in
    a)
        yt-dlp -x -f '251-dash/251/ba*' --audio-quality 0 "$@"
        ;;

    v)
        [ $# -lt 2 ] && usage
        fmt="$1"; shift
        yt-dlp -f 'b' --remux-video "$fmt" "$@"
        ;;

    *) usage ;;
esac
